// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClb8ljjFlEK4rC0xZ_NODFauG_D-0ZYPU',
    appId: '1:627019986151:web:c1bbceb4e2f97854dc1e42',
    messagingSenderId: '627019986151',
    projectId: 'digitrecognitionapp-c9263',
    authDomain: 'digitrecognitionapp-c9263.firebaseapp.com',
    storageBucket: 'digitrecognitionapp-c9263.firebasestorage.app',
    measurementId: 'G-J9MBPF5MFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSCb4T5hjNaqi2yKL2FcwurDr0BmTpmJA',
    appId: '1:627019986151:android:4396e50801538d3cdc1e42',
    messagingSenderId: '627019986151',
    projectId: 'digitrecognitionapp-c9263',
    storageBucket: 'digitrecognitionapp-c9263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAACgPn5K5sHsapKF4FfNBV-1NYQ8r8CWk',
    appId: '1:627019986151:ios:876baaa577ca8348dc1e42',
    messagingSenderId: '627019986151',
    projectId: 'digitrecognitionapp-c9263',
    storageBucket: 'digitrecognitionapp-c9263.firebasestorage.app',
    iosBundleId: 'com.example.digitRecognitionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAACgPn5K5sHsapKF4FfNBV-1NYQ8r8CWk',
    appId: '1:627019986151:ios:876baaa577ca8348dc1e42',
    messagingSenderId: '627019986151',
    projectId: 'digitrecognitionapp-c9263',
    storageBucket: 'digitrecognitionapp-c9263.firebasestorage.app',
    iosBundleId: 'com.example.digitRecognitionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClb8ljjFlEK4rC0xZ_NODFauG_D-0ZYPU',
    appId: '1:627019986151:web:d9b3ef6b6af27882dc1e42',
    messagingSenderId: '627019986151',
    projectId: 'digitrecognitionapp-c9263',
    authDomain: 'digitrecognitionapp-c9263.firebaseapp.com',
    storageBucket: 'digitrecognitionapp-c9263.firebasestorage.app',
    measurementId: 'G-KG5SMGZ43P',
  );
}
